apiVersion: v1
kind: Service
metadata:
  name: websocket-app-service
spec:
  type: NodePort
  selector:
    app: websocket-app
  ports:
    - targetPort: 8000
      port: 80
      nodePort: 30007
      protocol: TCP